services:
  app:
    container_name: jobflow-app
    build:
      context: .
      target: release
    env_file:
      - .env
    environment:
      PORT: ${PORT},
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "3000:${PORT}"



